# Generated by Django 5.1.4 on 2024-12-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.TextField(verbose_name='')),
                ('date', models.DateField()),
            ],
        ),
    ]
