# Generated by Django 5.1.4 on 2025-01-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('chandigarh', 'sector 43'), ('mohali', 'punjab'), ('location3', 'Location 3')], max_length=100)),
                ('date', models.DateField()),
                ('car', models.CharField(choices=[('scoda', 'm24'), ('bmw', 'c22'), ('car3', 'Car Model 3')], max_length=100)),
            ],
        ),
    ]
